DROP TABLE IF EXISTS Employers;

CREATE TABLE Employers (
    Username NVARCHAR(50) PRIMARY KEY,
    CompanyName NVARCHAR(50) NOT NULL,
    AddressLine NVARCHAR(50) NOT NULL,
    City NVARCHAR(50) NOT NULL,
    State NVARCHAR(50) NOT NULL,
    ZipCode NVARCHAR(50) NOT NULL,
    ContactFirstName NVARCHAR(50) NOT NULL,
    ContactLastName NVARCHAR(50) NOT NULL,
    ContactPhone NVARCHAR(50) NOT NULL,
    ContactEmail NVARCHAR(50) NOT NULL
);