DROP TABLE IF EXISTS JobPosts;

CREATE TABLE JobPosts (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EmployerID NVARCHAR(50) NOT NULL,
    JobName NVARCHAR(50) NOT NULL,
    CompanyJobID NVARCHAR(50) NOT NULL,
    ContactFirstName NVARCHAR(50) NOT NULL,
    ContactLastName NVARCHAR(50) NOT NULL,
    ContactPhone NVARCHAR(50) NOT NULL,
    ContactEmail NVARCHAR(50) NOT NULL,
    StartDate NVARCHAR(50) NOT NULL,
    EndDate NVARCHAR(50) NOT NULL,
    StartTime NVARCHAR(50) NOT NULL,
    EndTime NVARCHAR(50) NOT NULL,
    HourlyRate NVARCHAR(50) NOT NULL
);